version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '18869:15672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 70s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - rswd_188679_network
  
  reservation-service:
    image: jjayjohnny/rswd_188679_reservation_service:latest
    container_name: reservation-service
    depends_on:
      - rabbitmq
      - reservation-service-db
    environment:
      ConnectionStrings__RabbitMQ: amqp://guest:guest@rabbitmq:5672
      ConnectionStrings__MySql: Server=admin-mysql_db;Database=rswd_188679_reservation_service;User=root;Password=student;SslMode=none;
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 70s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - rswd_188679_network
      - admin-mysql_default

  offer-service:
    image: jjayjohnny/rswd_188679_offer_service:latest
    container_name: offer-service
    depends_on:
      - rabbitmq
      - offer-service-db
    environment:
      ConnectionStrings__RabbitMQ: amqp://guest:guest@rabbitmq:5672
      ConnectionStrings__MySql: Server=admin-mysql_db;Database=rswd_188679_offer_service;User=root;Password=student;SslMode=none;
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 70s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
    - rswd_188679_network
    - admin-mysql_default

  payment-service:
    image: jjayjohnny/rswd_188679_payment_service:latest
    container_name: payment-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      MongoDBSettings__ConnectionString: mongodb://root:student@admin-mongodb_mongo:27017/rswd_188679_PaymentsDB
      ConnectionStrings__RabbitMQ: amqp://guest:guest@rabbitmq:5672
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 70s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
    - rswd_188679_network
    - admin-mongodb_default
   
  api-gateway:
    image: jjayjohnny/rswd_188679_api_gateway:latest
    container_name: api-gateway
    ports:
      - '18868:8080'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 70s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - rswd_188679_network  

  frontend:
    image: jjayjohnny/rswd_188679_frontend:latest
    container_name: frontend
    ports:
      - '18867:80'
    environment:
      API_URL: http://api-gateway:8080/api
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 70s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - rswd_188679_network

networks:
  rswd_188679_network:
  admin-mysql_default:
    external: true
  admin-mongodb_default:
    external: true
    