export const FLIGHTS = [
  {
    id: 'flight1',
    departure: 'New York (JFK)',
    arrival: 'London (LHR)',
    price: 850,
    datetime: '2025-04-10T15:30',
    duration: '7h 30m',
    airline: 'British Airways',
    seatsFirstClass: 5,
    seatsEconomy: 20,
  },
  {
    id: 'flight2',
    departure: 'Los Angeles (LAX)',
    arrival: 'Tokyo (NRT)',
    price: 1500,
    datetime: '2025-04-12T10:00',
    duration: '11h 45m',
    airline: 'ANA',
    seatsFirstClass: 2,
    seatsEconomy: 15,
  },
  {
    id: 'flight3',
    departure: 'Paris (CDG)',
    arrival: 'Berlin (TXL)',
    price: 180,
    datetime: '2025-04-15T08:00',
    duration: '1h 45m',
    airline: 'Air France',
    seatsFirstClass: 3,
    seatsEconomy: 30,
  },
  {
    id: 'flight4',
    departure: 'Sydney (SYD)',
    arrival: 'Auckland (AKL)',
    price: 420,
    datetime: '2025-04-20T13:45',
    duration: '3h 5m',
    airline: 'Qantas',
    seatsFirstClass: 4,
    seatsEconomy: 25,
  },
  {
    id: 'flight5',
    departure: 'Rome (FCO)',
    arrival: 'Madrid (MAD)',
    price: 200,
    datetime: '2025-04-22T14:30',
    duration: '2h 30m',
    airline: 'Iberia',
    seatsFirstClass: 2,
    seatsEconomy: 20,
  },
  {
    id: 'flight6',
    departure: 'Dubai (DXB)',
    arrival: 'Mumbai (BOM)',
    price: 500,
    datetime: '2025-04-25T22:15',
    duration: '3h 30m',
    airline: 'Emirates',
    seatsFirstClass: 3,
    seatsEconomy: 18,
  },
  {
    id: 'flight7',
    departure: 'Berlin (TXL)',
    arrival: 'Amsterdam (AMS)',
    price: 120,
    datetime: '2025-04-28T16:00',
    duration: '1h 15m',
    airline: 'KLM',
    seatsFirstClass: 5,
    seatsEconomy: 25,
  },
  {
    id: 'flight8',
    departure: 'Tokyo (NRT)',
    arrival: 'Seoul (ICN)',
    price: 350,
    datetime: '2025-04-30T12:45',
    duration: '2h 30m',
    airline: 'Korean Air',
    seatsFirstClass: 3,
    seatsEconomy: 22,
  },
  {
    id: 'flight9',
    departure: 'San Francisco (SFO)',
    arrival: 'Chicago (ORD)',
    price: 200,
    datetime: '2025-05-01T09:30',
    duration: '4h 15m',
    airline: 'United Airlines',
    seatsFirstClass: 4,
    seatsEconomy: 28,
  },
  {
    id: 'flight10',
    departure: 'Los Angeles (LAX)',
    arrival: 'Las Vegas (LAS)',
    price: 150,
    datetime: '2025-05-05T18:00',
    duration: '1h 10m',
    airline: 'American Airlines',
    seatsFirstClass: 2,
    seatsEconomy: 15,
  },
];
