export const FLIGHTS = [
  {
    id: 'flight1',
    departure: 'New York (JFK)',
    arrival: 'London (LHR)',
    price: 850,
    datetime: '2025-04-10T15:30',
    duration: '7h 30m',
    airline: 'British Airways',
    seatsFirstClass: 5,
    seatsEconomy: 20,
  },
  {
    id: 'flight2',
    departure: 'Los Angeles (LAX)',
    arrival: 'Tokyo (NRT)',
    price: 1500,
    datetime: '2025-04-12T10:00',
    duration: '11h 45m',
    airline: 'ANA',
    seatsFirstClass: 2,
    seatsEconomy: 15,
  },
  {
    id: 'flight3',
    departure: 'Paris (CDG)',
    arrival: 'Berlin (TXL)',
    price: 180,
    datetime: '2025-04-15T08:00',
    duration: '1h 45m',
    airline: 'Air France',
    seatsFirstClass: 3,
    seatsEconomy: 30,
  },
  {
    id: 'flight4',
    departure: 'Sydney (SYD)',
    arrival: 'Auckland (AKL)',
    price: 420,
    datetime: '2025-04-20T13:45',
    duration: '3h 5m',
    airline: 'Qantas',
    seatsFirstClass: 4,
    seatsEconomy: 25,
  },
  {
    id: 'flight5',
    departure: 'Rome (FCO)',
    arrival: 'Madrid (MAD)',
    price: 200,
    datetime: '2025-04-22T14:30',
    duration: '2h 30m',
    airline: 'Iberia',
    seatsFirstClass: 2,
    seatsEconomy: 20,
  },
  {
    id: 'flight6',
    departure: 'Dubai (DXB)',
    arrival: 'Mumbai (BOM)',
    price: 500,
    datetime: '2025-04-25T22:15',
    duration: '3h 30m',
    airline: 'Emirates',
    seatsFirstClass: 3,
    seatsEconomy: 18,
  },
  {
    id: 'flight7',
    departure: 'Berlin (TXL)',
    arrival: 'Amsterdam (AMS)',
    price: 120,
    datetime: '2025-04-28T16:00',
    duration: '1h 15m',
    airline: 'KLM',
    seatsFirstClass: 5,
    seatsEconomy: 25,
  },
  {
    id: 'flight8',
    departure: 'Tokyo (NRT)',
    arrival: 'Seoul (ICN)',
    price: 350,
    datetime: '2025-04-30T12:45',
    duration: '2h 30m',
    airline: 'Korean Air',
    seatsFirstClass: 3,
    seatsEconomy: 22,
  },
  {
    id: 'flight9',
    departure: 'San Francisco (SFO)',
    arrival: 'Chicago (ORD)',
    price: 200,
    datetime: '2025-05-01T09:30',
    duration: '4h 15m',
    airline: 'United Airlines',
    seatsFirstClass: 4,
    seatsEconomy: 28,
  },
  {
    id: 'flight10',
    departure: 'Los Angeles (LAX)',
    arrival: 'Las Vegas (LAS)',
    price: 150,
    datetime: '2025-05-05T18:00',
    duration: '1h 10m',
    airline: 'American Airlines',
    seatsFirstClass: 2,
    seatsEconomy: 15,
  },
  {
    id: 'flight11',
    departure: 'New York (JFK)',
    arrival: 'Paris (CDG)',
    price: 950,
    datetime: '2025-04-12T18:30',
    duration: '8h 15m',
    airline: 'Air France',
    seatsFirstClass: 6,
    seatsEconomy: 25,
  },
  {
    id: 'flight12',
    departure: 'London (LHR)',
    arrival: 'Dubai (DXB)',
    price: 1200,
    datetime: '2025-04-15T22:00',
    duration: '7h 10m',
    airline: 'Emirates',
    seatsFirstClass: 4,
    seatsEconomy: 30,
  },
  {
    id: 'flight13',
    departure: 'Los Angeles (LAX)',
    arrival: 'Singapore (SIN)',
    price: 1800,
    datetime: '2025-04-17T14:45',
    duration: '16h 20m',
    airline: 'Singapore Airlines',
    seatsFirstClass: 3,
    seatsEconomy: 12,
  },
  {
    id: 'flight14',
    departure: 'Sydney (SYD)',
    arrival: 'Singapore (SIN)',
    price: 700,
    datetime: '2025-04-19T21:30',
    duration: '8h 5m',
    airline: 'Qantas',
    seatsFirstClass: 4,
    seatsEconomy: 35,
  },
  {
    id: 'flight15',
    departure: 'Rome (FCO)',
    arrival: 'London (LHR)',
    price: 220,
    datetime: '2025-04-25T10:00',
    duration: '2h 20m',
    airline: 'British Airways',
    seatsFirstClass: 3,
    seatsEconomy: 30,
  },
  {
    id: 'flight16',
    departure: 'Tokyo (NRT)',
    arrival: 'Los Angeles (LAX)',
    price: 1500,
    datetime: '2025-04-28T08:00',
    duration: '10h 50m',
    airline: 'ANA',
    seatsFirstClass: 4,
    seatsEconomy: 25,
  },
  {
    id: 'flight17',
    departure: 'New York (JFK)',
    arrival: 'Dubai (DXB)',
    price: 1100,
    datetime: '2025-05-01T12:30',
    duration: '12h 45m',
    airline: 'Emirates',
    seatsFirstClass: 5,
    seatsEconomy: 40,
  },
  {
    id: 'flight18',
    departure: 'Paris (CDG)',
    arrival: 'Berlin (TXL)',
    price: 150,
    datetime: '2025-05-02T13:00',
    duration: '1h 50m',
    airline: 'Lufthansa',
    seatsFirstClass: 2,
    seatsEconomy: 18,
  },
  {
    id: 'flight19',
    departure: 'London (LHR)',
    arrival: 'Madrid (MAD)',
    price: 180,
    datetime: '2025-05-04T17:45',
    duration: '2h 10m',
    airline: 'Iberia',
    seatsFirstClass: 3,
    seatsEconomy: 20,
  },
  {
    id: 'flight20',
    departure: 'San Francisco (SFO)',
    arrival: 'Las Vegas (LAS)',
    price: 120,
    datetime: '2025-05-07T19:15',
    duration: '1h 25m',
    airline: 'JetBlue Airways',
    seatsFirstClass: 3,
    seatsEconomy: 25,
  },
  {
    id: 'flight21',
    departure: 'New York (JFK)',
    arrival: 'Dubai (DXB)',
    price: 1300,
    datetime: '2025-04-15T09:30',
    duration: '12h 10m',
    airline: 'Qatar Airways',
    seatsFirstClass: 3,
    seatsEconomy: 20,
  },
  {
    id: 'flight22',
    departure: 'Los Angeles (LAX)',
    arrival: 'London (LHR)',
    price: 950,
    datetime: '2025-04-18T17:30',
    duration: '10h 25m',
    airline: 'British Airways',
    seatsFirstClass: 4,
    seatsEconomy: 22,
  },
  {
    id: 'flight23',
    departure: 'Sydney (SYD)',
    arrival: 'Los Angeles (LAX)',
    price: 1500,
    datetime: '2025-04-20T11:00',
    duration: '13h 15m',
    airline: 'Qantas',
    seatsFirstClass: 2,
    seatsEconomy: 18,
  },
  {
    id: 'flight24',
    departure: 'Paris (CDG)',
    arrival: 'Rome (FCO)',
    price: 180,
    datetime: '2025-04-23T07:00',
    duration: '2h 5m',
    airline: 'Air France',
    seatsFirstClass: 3,
    seatsEconomy: 25,
  },
  {
    id: 'flight25',
    departure: 'Tokyo (NRT)',
    arrival: 'Hong Kong (HKG)',
    price: 400,
    datetime: '2025-04-26T09:00',
    duration: '5h 30m',
    airline: 'Cathay Pacific',
    seatsFirstClass: 2,
    seatsEconomy: 30,
  },
  {
    id: 'flight26',
    departure: 'London (LHR)',
    arrival: 'New York (JFK)',
    price: 850,
    datetime: '2025-04-29T21:00',
    duration: '8h 0m',
    airline: 'American Airlines',
    seatsFirstClass: 4,
    seatsEconomy: 30,
  },
  {
    id: 'flight27',
    departure: 'San Francisco (SFO)',
    arrival: 'Paris (CDG)',
    price: 1050,
    datetime: '2025-05-02T16:00',
    duration: '10h 15m',
    airline: 'United Airlines',
    seatsFirstClass: 5,
    seatsEconomy: 28,
  },
  {
    id: 'flight28',
    departure: 'Rome (FCO)',
    arrival: 'Berlin (TXL)',
    price: 170,
    datetime: '2025-05-03T11:30',
    duration: '2h 20m',
    airline: 'Alitalia',
    seatsFirstClass: 3,
    seatsEconomy: 22,
  },
  {
    id: 'flight29',
    departure: 'Dubai (DXB)',
    arrival: 'Singapore (SIN)',
    price: 800,
    datetime: '2025-05-06T16:00',
    duration: '7h 30m',
    airline: 'Emirates',
    seatsFirstClass: 2,
    seatsEconomy: 30,
  },
  {
    id: 'flight30',
    departure: 'Los Angeles (LAX)',
    arrival: 'New York (JFK)',
    price: 300,
    datetime: '2025-05-10T14:00',
    duration: '5h 50m',
    airline: 'Delta Airlines',
    seatsFirstClass: 3,
    seatsEconomy: 25,
  },
];
